//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: TestProto.proto
//
//package com.ucsmy.rabbitmq.protobuf;
//
//import com.google.protobuf.*;
//
//public final class TestProtobuf {
//  private TestProtobuf() {}
//  public static void registerAllExtensions(
//      ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      ExtensionRegistry registry) {
//    registerAllExtensions(
//        (ExtensionRegistryLite) registry);
//  }
//  public interface InfoOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:protobuf.Info)
//      MessageOrBuilder {
//
//    /**
//     * <code>required int32 ID = 1;</code>
//     */
//    boolean hasID();
//    /**
//     * <code>required int32 ID = 1;</code>
//     */
//    int getID();
//
//    /**
//     * <code>required string title = 2;</code>
//     */
//    boolean hasTitle();
//    /**
//     * <code>required string title = 2;</code>
//     */
//    String getTitle();
//    /**
//     * <code>required string title = 2;</code>
//     */
//    ByteString
//        getTitleBytes();
//
//    /**
//     * <code>required string content = 3;</code>
//     */
//    boolean hasContent();
//    /**
//     * <code>required string content = 3;</code>
//     */
//    String getContent();
//    /**
//     * <code>required string content = 3;</code>
//     */
//    ByteString
//        getContentBytes();
//  }
//  /**
//   * Protobuf type {@code protobuf.Info}
//   */
//  public  static final class Info extends GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:protobuf.Info)
//      InfoOrBuilder {
//    // Use Info.newBuilder() to construct.
//    private Info(GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private Info() {
//      iD_ = 0;
//      title_ = "";
//      content_ = "";
//    }
//
//    @Override
//    public final UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private Info(
//        CodedInputStream input,
//        ExtensionRegistryLite extensionRegistry)
//        throws InvalidProtocolBufferException {
//      this();
//      int mutable_bitField0_ = 0;
//      UnknownFieldSet.Builder unknownFields =
//          UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            default: {
//              if (!parseUnknownField(input, unknownFields,
//                                     extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//            case 8: {
//              bitField0_ |= 0x00000001;
//              iD_ = input.readInt32();
//              break;
//            }
//            case 18: {
//              ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000002;
//              title_ = bs;
//              break;
//            }
//            case 26: {
//              ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000004;
//              content_ = bs;
//              break;
//            }
//          }
//        }
//      } catch (InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final Descriptors.Descriptor
//        getDescriptor() {
//      return com.test.protobuf.TestProtobuf.internal_static_protobuf_Info_descriptor;
//    }
//
//    protected GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.test.protobuf.TestProtobuf.internal_static_protobuf_Info_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.test.protobuf.TestProtobuf.Info.class, com.test.protobuf.TestProtobuf.Info.Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int ID_FIELD_NUMBER = 1;
//    private int iD_;
//    /**
//     * <code>required int32 ID = 1;</code>
//     */
//    public boolean hasID() {
//      return ((bitField0_ & 0x00000001) == 0x00000001);
//    }
//    /**
//     * <code>required int32 ID = 1;</code>
//     */
//    public int getID() {
//      return iD_;
//    }
//
//    public static final int TITLE_FIELD_NUMBER = 2;
//    private volatile Object title_;
//    /**
//     * <code>required string title = 2;</code>
//     */
//    public boolean hasTitle() {
//      return ((bitField0_ & 0x00000002) == 0x00000002);
//    }
//    /**
//     * <code>required string title = 2;</code>
//     */
//    public String getTitle() {
//      Object ref = title_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        ByteString bs =
//            (ByteString) ref;
//        String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          title_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>required string title = 2;</code>
//     */
//    public ByteString
//        getTitleBytes() {
//      Object ref = title_;
//      if (ref instanceof String) {
//        ByteString b =
//            ByteString.copyFromUtf8(
//                (String) ref);
//        title_ = b;
//        return b;
//      } else {
//        return (ByteString) ref;
//      }
//    }
//
//    public static final int CONTENT_FIELD_NUMBER = 3;
//    private volatile Object content_;
//    /**
//     * <code>required string content = 3;</code>
//     */
//    public boolean hasContent() {
//      return ((bitField0_ & 0x00000004) == 0x00000004);
//    }
//    /**
//     * <code>required string content = 3;</code>
//     */
//    public String getContent() {
//      Object ref = content_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        ByteString bs =
//            (ByteString) ref;
//        String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          content_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>required string content = 3;</code>
//     */
//    public ByteString
//        getContentBytes() {
//      Object ref = content_;
//      if (ref instanceof String) {
//        ByteString b =
//            ByteString.copyFromUtf8(
//                (String) ref);
//        content_ = b;
//        return b;
//      } else {
//        return (ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      if (!hasID()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      if (!hasTitle()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      if (!hasContent()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    public void writeTo(CodedOutputStream output)
//                        throws java.io.IOException {
//      if (((bitField0_ & 0x00000001) == 0x00000001)) {
//        output.writeInt32(1, iD_);
//      }
//      if (((bitField0_ & 0x00000002) == 0x00000002)) {
//        GeneratedMessageV3.writeString(output, 2, title_);
//      }
//      if (((bitField0_ & 0x00000004) == 0x00000004)) {
//        GeneratedMessageV3.writeString(output, 3, content_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) == 0x00000001)) {
//        size += CodedOutputStream
//          .computeInt32Size(1, iD_);
//      }
//      if (((bitField0_ & 0x00000002) == 0x00000002)) {
//        size += GeneratedMessageV3.computeStringSize(2, title_);
//      }
//      if (((bitField0_ & 0x00000004) == 0x00000004)) {
//        size += GeneratedMessageV3.computeStringSize(3, content_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    private static final long serialVersionUID = 0L;
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.test.protobuf.TestProtobuf.Info)) {
//        return super.equals(obj);
//      }
//      com.test.protobuf.TestProtobuf.Info other = (com.test.protobuf.TestProtobuf.Info) obj;
//
//      boolean result = true;
//      result = result && (hasID() == other.hasID());
//      if (hasID()) {
//        result = result && (getID()
//            == other.getID());
//      }
//      result = result && (hasTitle() == other.hasTitle());
//      if (hasTitle()) {
//        result = result && getTitle()
//            .equals(other.getTitle());
//      }
//      result = result && (hasContent() == other.hasContent());
//      if (hasContent()) {
//        result = result && getContent()
//            .equals(other.getContent());
//      }
//      result = result && unknownFields.equals(other.unknownFields);
//      return result;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptorForType().hashCode();
//      if (hasID()) {
//        hash = (37 * hash) + ID_FIELD_NUMBER;
//        hash = (53 * hash) + getID();
//      }
//      if (hasTitle()) {
//        hash = (37 * hash) + TITLE_FIELD_NUMBER;
//        hash = (53 * hash) + getTitle().hashCode();
//      }
//      if (hasContent()) {
//        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
//        hash = (53 * hash) + getContent().hashCode();
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.test.protobuf.TestProtobuf.Info parseFrom(
//        ByteString data)
//        throws InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseFrom(
//        ByteString data,
//        ExtensionRegistryLite extensionRegistry)
//        throws InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseFrom(byte[] data)
//        throws InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseFrom(
//        byte[] data,
//        ExtensionRegistryLite extensionRegistry)
//        throws InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseFrom(
//        java.io.InputStream input,
//        ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseDelimitedFrom(
//        java.io.InputStream input,
//        ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseFrom(
//        CodedInputStream input)
//        throws java.io.IOException {
//      return GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.test.protobuf.TestProtobuf.Info parseFrom(
//        CodedInputStream input,
//        ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.test.protobuf.TestProtobuf.Info prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code protobuf.Info}
//     */
//    public static final class Builder extends
//        GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:protobuf.Info)
//        com.test.protobuf.TestProtobuf.InfoOrBuilder {
//      public static final Descriptors.Descriptor
//          getDescriptor() {
//        return com.test.protobuf.TestProtobuf.internal_static_protobuf_Info_descriptor;
//      }
//
//      protected GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.test.protobuf.TestProtobuf.internal_static_protobuf_Info_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.test.protobuf.TestProtobuf.Info.class, com.test.protobuf.TestProtobuf.Info.Builder.class);
//      }
//
//      // Construct using com.test.protobuf.TestProtobuf.Info.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      public Builder clear() {
//        super.clear();
//        iD_ = 0;
//        bitField0_ = (bitField0_ & ~0x00000001);
//        title_ = "";
//        bitField0_ = (bitField0_ & ~0x00000002);
//        content_ = "";
//        bitField0_ = (bitField0_ & ~0x00000004);
//        return this;
//      }
//
//      public Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.test.protobuf.TestProtobuf.internal_static_protobuf_Info_descriptor;
//      }
//
//      public com.test.protobuf.TestProtobuf.Info getDefaultInstanceForType() {
//        return com.test.protobuf.TestProtobuf.Info.getDefaultInstance();
//      }
//
//      public com.test.protobuf.TestProtobuf.Info build() {
//        com.test.protobuf.TestProtobuf.Info result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      public com.test.protobuf.TestProtobuf.Info buildPartial() {
//        com.test.protobuf.TestProtobuf.Info result = new com.test.protobuf.TestProtobuf.Info(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
//          to_bitField0_ |= 0x00000001;
//        }
//        result.iD_ = iD_;
//        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
//          to_bitField0_ |= 0x00000002;
//        }
//        result.title_ = title_;
//        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
//          to_bitField0_ |= 0x00000004;
//        }
//        result.content_ = content_;
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      public Builder clone() {
//        return (Builder) super.clone();
//      }
//      public Builder setField(
//          Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.setField(field, value);
//      }
//      public Builder clearField(
//          Descriptors.FieldDescriptor field) {
//        return (Builder) super.clearField(field);
//      }
//      public Builder clearOneof(
//          Descriptors.OneofDescriptor oneof) {
//        return (Builder) super.clearOneof(oneof);
//      }
//      public Builder setRepeatedField(
//          Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return (Builder) super.setRepeatedField(field, index, value);
//      }
//      public Builder addRepeatedField(
//          Descriptors.FieldDescriptor field,
//          Object value) {
//        return (Builder) super.addRepeatedField(field, value);
//      }
//      public Builder mergeFrom(Message other) {
//        if (other instanceof com.test.protobuf.TestProtobuf.Info) {
//          return mergeFrom((com.test.protobuf.TestProtobuf.Info)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.test.protobuf.TestProtobuf.Info other) {
//        if (other == com.test.protobuf.TestProtobuf.Info.getDefaultInstance()) return this;
//        if (other.hasID()) {
//          setID(other.getID());
//        }
//        if (other.hasTitle()) {
//          bitField0_ |= 0x00000002;
//          title_ = other.title_;
//          onChanged();
//        }
//        if (other.hasContent()) {
//          bitField0_ |= 0x00000004;
//          content_ = other.content_;
//          onChanged();
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      public final boolean isInitialized() {
//        if (!hasID()) {
//          return false;
//        }
//        if (!hasTitle()) {
//          return false;
//        }
//        if (!hasContent()) {
//          return false;
//        }
//        return true;
//      }
//
//      public Builder mergeFrom(
//          CodedInputStream input,
//          ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        com.test.protobuf.TestProtobuf.Info parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (InvalidProtocolBufferException e) {
//          parsedMessage = (com.test.protobuf.TestProtobuf.Info) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private int iD_ ;
//      /**
//       * <code>required int32 ID = 1;</code>
//       */
//      public boolean hasID() {
//        return ((bitField0_ & 0x00000001) == 0x00000001);
//      }
//      /**
//       * <code>required int32 ID = 1;</code>
//       */
//      public int getID() {
//        return iD_;
//      }
//      /**
//       * <code>required int32 ID = 1;</code>
//       */
//      public Builder setID(int value) {
//        bitField0_ |= 0x00000001;
//        iD_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required int32 ID = 1;</code>
//       */
//      public Builder clearID() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        iD_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private Object title_ = "";
//      /**
//       * <code>required string title = 2;</code>
//       */
//      public boolean hasTitle() {
//        return ((bitField0_ & 0x00000002) == 0x00000002);
//      }
//      /**
//       * <code>required string title = 2;</code>
//       */
//      public String getTitle() {
//        Object ref = title_;
//        if (!(ref instanceof String)) {
//          ByteString bs =
//              (ByteString) ref;
//          String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            title_ = s;
//          }
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>required string title = 2;</code>
//       */
//      public ByteString
//          getTitleBytes() {
//        Object ref = title_;
//        if (ref instanceof String) {
//          ByteString b =
//              ByteString.copyFromUtf8(
//                  (String) ref);
//          title_ = b;
//          return b;
//        } else {
//          return (ByteString) ref;
//        }
//      }
//      /**
//       * <code>required string title = 2;</code>
//       */
//      public Builder setTitle(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        title_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string title = 2;</code>
//       */
//      public Builder clearTitle() {
//        bitField0_ = (bitField0_ & ~0x00000002);
//        title_ = getDefaultInstance().getTitle();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string title = 2;</code>
//       */
//      public Builder setTitleBytes(
//          ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        title_ = value;
//        onChanged();
//        return this;
//      }
//
//      private Object content_ = "";
//      /**
//       * <code>required string content = 3;</code>
//       */
//      public boolean hasContent() {
//        return ((bitField0_ & 0x00000004) == 0x00000004);
//      }
//      /**
//       * <code>required string content = 3;</code>
//       */
//      public String getContent() {
//        Object ref = content_;
//        if (!(ref instanceof String)) {
//          ByteString bs =
//              (ByteString) ref;
//          String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            content_ = s;
//          }
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>required string content = 3;</code>
//       */
//      public ByteString
//          getContentBytes() {
//        Object ref = content_;
//        if (ref instanceof String) {
//          ByteString b =
//              ByteString.copyFromUtf8(
//                  (String) ref);
//          content_ = b;
//          return b;
//        } else {
//          return (ByteString) ref;
//        }
//      }
//      /**
//       * <code>required string content = 3;</code>
//       */
//      public Builder setContent(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000004;
//        content_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string content = 3;</code>
//       */
//      public Builder clearContent() {
//        bitField0_ = (bitField0_ & ~0x00000004);
//        content_ = getDefaultInstance().getContent();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string content = 3;</code>
//       */
//      public Builder setContentBytes(
//          ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000004;
//        content_ = value;
//        onChanged();
//        return this;
//      }
//      public final Builder setUnknownFields(
//          final UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      public final Builder mergeUnknownFields(
//          final UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:protobuf.Info)
//    }
//
//    // @@protoc_insertion_point(class_scope:protobuf.Info)
//    private static final com.test.protobuf.TestProtobuf.Info DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.test.protobuf.TestProtobuf.Info();
//    }
//
//    public static com.test.protobuf.TestProtobuf.Info getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    @Deprecated public static final Parser<Info>
//        PARSER = new AbstractParser<Info>() {
//      public Info parsePartialFrom(
//          CodedInputStream input,
//          ExtensionRegistryLite extensionRegistry)
//          throws InvalidProtocolBufferException {
//          return new Info(input, extensionRegistry);
//      }
//    };
//
//    public static Parser<Info> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public Parser<Info> getParserForType() {
//      return PARSER;
//    }
//
//    public com.test.protobuf.TestProtobuf.Info getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final Descriptors.Descriptor
//    internal_static_protobuf_Info_descriptor;
//  private static final
//    GeneratedMessageV3.FieldAccessorTable
//      internal_static_protobuf_Info_fieldAccessorTable;
//
//  public static Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  Descriptors.FileDescriptor
//      descriptor;
//  static {
//    String[] descriptorData = {
//      "\n\017TestProto.proto\022\010protobuf\"2\n\004Info\022\n\n\002I" +
//      "D\030\001 \002(\005\022\r\n\005title\030\002 \002(\t\022\017\n\007content\030\003 \002(\tB" +
//      "!\n\021com.test.protobufB\014TestProtobuf"
//    };
//    Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
//        new Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
//          public ExtensionRegistry assignDescriptors(
//              Descriptors.FileDescriptor root) {
//            descriptor = root;
//            return null;
//          }
//        };
//    Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new Descriptors.FileDescriptor[] {
//        }, assigner);
//    internal_static_protobuf_Info_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_protobuf_Info_fieldAccessorTable = new
//      GeneratedMessageV3.FieldAccessorTable(
//        internal_static_protobuf_Info_descriptor,
//        new String[] { "ID", "Title", "Content", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
